# Generated by Django 5.1.7 on 2025-03-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceimage",
            name="metadata",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="transformedimage",
            name="metadata",
            field=models.JSONField(blank=True),
        ),
    ]
