# Generated by Django 5.1.7 on 2025-03-26 09:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_sourceimage_file_transformedimage_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="sourceimage", name="url",),
        migrations.RemoveField(model_name="transformedimage", name="url",),
        migrations.AlterField(
            model_name="sourceimage",
            name="file",
            field=models.ImageField(upload_to=api.models.unique_image_path),
        ),
        migrations.AlterField(
            model_name="transformedimage",
            name="file",
            field=models.ImageField(upload_to=api.models.unique_image_path),
        ),
    ]
