# Generated by Django 5.1.7 on 2025-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_sourceimage_url_remove_transformedimage_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationtask",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[("JPEG", "Jpeg"), ("PNG", "Png")],
                max_length=10,
                null=True,
            ),
        ),
    ]
