# Generated by Django 5.1.7 on 2025-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_transformationtask_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformationtask",
            name="format",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
