# Generated by Django 5.1.7 on 2025-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_transformationtask_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationtask",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
