"""
Django settings for image_processing_service project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import hashlib
import os
import sys
from datetime import timedelta
from pathlib import Path
from typing import Any, Dict

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Note: In a production environment, you should set this in an environment variabl
if "test" in sys.argv:
    SECRET_KEY: str | None = "dummy_secret_key_for_testing"
else:
    SECRET_KEY: str | None = os.getenv("DJANGO_SECRET_KEY")
    if not SECRET_KEY:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS: list = ["127.0.0.1", "localhost"] + os.getenv("ALLOWED_HOSTS", "").split(
    ","
)

# Security settings
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "True").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "True").lower() == "true"
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", 31536000))  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower() == "true"
)
SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "False").lower() == "true"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sites",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "django_celery_results",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "api",
    "image_processor",
    "storages",
    "corsheaders",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("ANON_THROTTLE_RATE", "100/day"),
        "user": os.getenv("USER_THROTTLE_RATE", "1000/day"),
        "dj_rest_auth": os.getenv("ANON_THROTTLE_RATE", "100/day"),
    },
}

REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "access",
    "JWT_AUTH_REFRESH_COOKIE": "refresh",
    "JWT_AUTH_HTTPONLY": True,
    "JWT_AUTH_SAMESITE": "Lax",
    "JWT_AUTH_SECURE": not DEBUG,
}

ROOT_URLCONF = "image_processing_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "image_processing_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "postgres"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "password"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }

# Base configuration
STORAGES: Dict[str, Dict[str, Any]] = {
    "default": {"BACKEND": ""},
    "staticfiles": {"BACKEND": ""},
}

if "test" in sys.argv:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STORAGES.update(
        {
            "default": {
                "BACKEND": "django.core.files.storage.InMemoryStorage",
            },
            "staticfiles": {
                "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
            },
        }
    )
else:
    # AWS configuration
    aws_config = {
        "access_key": os.environ.get("AWS_ACCESS_KEY_ID"),
        "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY"),
        "bucket_name": os.environ.get("AWS_STORAGE_BUCKET_NAME"),
        "region_name": os.environ.get("AWS_S3_REGION_NAME"),
    }

    missing = [key for key, val in aws_config.items() if not val]
    if missing:
        raise ImproperlyConfigured(
            f"Missing AWS credential(s) for S3 storage: {', '.join(missing)}"
        )

    STORAGES.update(
        {
            "default": {
                "BACKEND": "storages.backends.s3.S3Storage",
                "OPTIONS": aws_config,
            },
            "staticfiles": {
                "BACKEND": "storages.backends.s3.S3Storage",
                "OPTIONS": {**aws_config, "location": "static"},
            },
        }
    )


CACHE_REDIS_URL = os.environ.get("CACHE_REDIS_URL", "redis://localhost:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": CACHE_REDIS_URL,
        "TIMEOUT": int(
            os.environ.get("CACHE_TIMEOUT_SECONDS", 7200)
        ),  # 2 hours | This value should not exceed expired image cleanup time
        # "OPTIONS": {
        #     "MAX_ENTRIES": 1000,
        #     "CULL_FREQUENCY": 10,  # 10% of the cache will be cleared
        # when it reaches the limit
        # },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501 # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "api.User"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("ACCESS_TOKEN_LIFETIME", 5))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("REFRESH_TOKEN_LIFETIME", 60))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    # Use the same key Django uses so that tokens work in all environments
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # ... other settings you want to customize
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Debugpy settings
REMOTE_DEBUGGING_PORT = os.getenv("REMOTE_DEBUGGING_PORT")

if DEBUG and REMOTE_DEBUGGING_PORT:
    print("Remote debugging port is set, starting debugpy")
    DEBUG_PORT = int(REMOTE_DEBUGGING_PORT)
    print("Starting debugpy with port", DEBUG_PORT)

    try:
        import debugpy  # type: ignore

        debugpy.listen(("0.0.0.0", DEBUG_PORT))
        print(f"Debugger is listening on port {DEBUG_PORT}")
    except Exception as e:
        print(f"debugpy not available: {e}")

# Celery settings
if "test" in sys.argv:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = "memory://"  # In-memory broker for tests
    CELERY_RESULT_BACKEND = "django-db"  # Use django-db backend for tests
else:
    CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
    CELERY_RESULT_BACKEND = "django_celery_results.backends.database:DatabaseBackend"


# Celery beat settings
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = "Europe/Istanbul"

SENTRY_DSN: str | None = os.getenv("SENTRY_DSN")

if SENTRY_DSN:
    print("Sentry DSN is set, initializing Sentry SDK")
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        _experiments={
            # Set continuous_profiling_auto_start to True
            # to automatically start the profiler on when
            # possible.
            "continuous_profiling_auto_start": True,
        },
        # Add data like request headers and IP for users, if applicable;
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/
        # for more info
        send_default_pii=True,
    )

LOG_FILE_PATH = os.getenv("LOG_FILE_PATH", "/var/log/django/django.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "DEBUG",  # Log everything to the file
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_FILE_PATH,  # Log inside the mounted volume
            "maxBytes": 1024 * 1024 * 15,  # 15MB
            "backupCount": 5,  # Keep 5 rotated log files
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],  # Logs both to console and file
            "level": "DEBUG",
            "propagate": True,
        },
        "api": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        # You can add more specific loggers for your apps here
        # 'my_app': {
        #     'handlers': ['file'],
        #     'level': 'DEBUG',
        # },
    },
}

# Validation settings

IMAGE_MAX_PIXEL_SIZE = int(os.getenv("IMAGE_MAX_PIXEL_SIZE", 4096))
IMAGE_MIN_PIXEL_SIZE = int(os.getenv("IMAGE_MIN_PIXEL_SIZE", 100))
IMAGE_MAX_FILE_SIZE_IN_BYTES = int(
    os.getenv("IMAGE_MAX_FILE_SIZE_IN_BYTES", 10 * 1024 * 1024)
)

# ---------------------------------------------------------------------------
# CORS / Cookie auth tweaks
# ---------------------------------------------------------------------------
# If ``django-cors-headers`` is installed we want to allow credentials so that
# browsers will send the HttpOnly cookies along with cross-origin XHR requests.
CORS_ALLOW_CREDENTIALS = True
# Allow localhost on the frontend port during development (silently ignore if
# ``django-cors-headers`` is not in INSTALLED_APPS).
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000"
).split(",")

SITE_ID = 1
